-- FHIR -> PG
-- boolean -> BOOLEAN 
-- integer -> INTEGER (INTEGER = 4 bytes = 4 * 8 bits = 32 bits)
CREATE DOMAIN string AS TEXT;
-- decimal -> DECIMAL
CREATE DOMAIN uri AS TEXT;
CREATE DOMAIN url AS TEXT;
CREATE DOMAIN canonical AS TEXT;
CREATE DOMAIN base64Binary AS TEXT;
CREATE DOMAIN instant AS TIMESTAMP WITH TIME ZONE;
-- date -> DATE
CREATE DOMAIN dateTime AS TIMESTAMP WITH TIME ZONE;
-- time -> TIME
CREATE DOMAIN code AS TEXT;
CREATE DOMAIN oid AS TEXT;
CREATE DOMAIN id AS TEXT;
CREATE DOMAIN markdown AS TEXT;
CREATE DOMAIN unsignedInt AS INTEGER
    CHECK (VALUE >= 0)
CREATE DOMAIN positiveInt AS INTEGER
    CHECK (Value > 0)
CREATE DOMAIN uuid AS TEXT;